export const learningConcepts = [
  {
    id: 'money-capital',
    label: 'Tư bản tiền tệ',
    shortLabel: 'T',
    summary: 'Điểm xuất phát của chu kỳ, nơi giá trị tồn tại dưới dạng tiền để mua đầu vào.',
    group: 'Tuần hoàn',
    order: 1,
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
  },
  {
    id: 'productive-capital',
    label: 'Tư bản sản xuất',
    shortLabel: 'SX',
    summary: 'Giai đoạn kết hợp tư liệu sản xuất và sức lao động để tạo ra giá trị mới.',
    group: 'Tuần hoàn',
    order: 2,
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
  },
  {
    id: 'commodity-capital',
    label: 'Tư bản hàng hóa',
    shortLabel: "H'",
    summary: 'Giá trị đã kết tinh trong hàng hóa nhưng chưa quay về dưới dạng tiền.',
    group: 'Tuần hoàn',
    order: 3,
    sourceLabels: ['Session 8', 'Capital Lab'],
  },
  {
    id: 'capital-circuit',
    label: 'Tuần hoàn tư bản',
    shortLabel: 'T→H→SX→H’→T’',
    summary: 'Chuỗi vận động của tư bản qua các hình thái tiền tệ, sản xuất và hàng hóa.',
    group: 'Tuần hoàn',
    order: 4,
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
  },
  {
    id: 'surplus-value',
    label: 'Giá trị thặng dư',
    shortLabel: 'm',
    summary: 'Phần giá trị mới dôi ra ngoài giá trị sức lao động, được tạo ra trong sản xuất.',
    group: 'Giá trị',
    order: 5,
    sourceLabels: ['Session 8', 'Session 10'],
  },
  {
    id: 'capital-turnover',
    label: 'Chu chuyển tư bản',
    shortLabel: 'Chu chuyển',
    summary: 'Tốc độ và nhịp lặp lại của chu kỳ tư bản khi giá trị quay về để khởi động vòng mới.',
    group: 'Điều kiện',
    order: 6,
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
  },
  {
    id: 'production-time',
    label: 'Thời gian sản xuất',
    shortLabel: 'SX time',
    summary: 'Khoảng thời gian tư bản nằm trong sản xuất và chưa thể trở lại thành tiền.',
    group: 'Điều kiện',
    order: 7,
    sourceLabels: ['Session 8'],
  },
  {
    id: 'circulation-time',
    label: 'Thời gian lưu thông',
    shortLabel: 'LT time',
    summary: 'Khoảng thời gian hàng hóa hoặc tiền nằm ngoài sản xuất để mua hoặc bán.',
    group: 'Điều kiện',
    order: 8,
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
  },
  {
    id: 'spatial-condition',
    label: 'Điều kiện không gian',
    shortLabel: 'Không gian',
    summary: 'Tổng tư bản phải đồng thời phân bố ở nhiều hình thái để chu kỳ không đứt gãy.',
    group: 'Điều kiện',
    order: 9,
    sourceLabels: ['Session 8'],
  },
  {
    id: 'temporal-condition',
    label: 'Điều kiện thời gian',
    shortLabel: 'Thời gian',
    summary: 'Các giai đoạn phải nối tiếp đúng nhịp để T’ quay về và mở được chu kỳ mới.',
    group: 'Điều kiện',
    order: 10,
    sourceLabels: ['Session 8'],
  },
  {
    id: 'reproduction',
    label: 'Tái sản xuất',
    shortLabel: 'Tái SX',
    summary: 'Quá trình lặp lại chu kỳ sản xuất để duy trì hoặc mở rộng vận động của tư bản.',
    group: 'Tái sản xuất',
    order: 11,
    sourceLabels: ['Session 10'],
  },
  {
    id: 'accumulation',
    label: 'Tích lũy tư bản',
    shortLabel: 'Tích lũy',
    summary: 'Biến một phần giá trị thặng dư thành tư bản mới để mở rộng sản xuất.',
    group: 'Tái sản xuất',
    order: 12,
    sourceLabels: ['Session 10'],
  },
  {
    id: 'profit',
    label: 'Lợi nhuận',
    shortLabel: 'p',
    summary: 'Hình thức biểu hiện ra ngoài của giá trị thặng dư khi so với tổng tư bản ứng trước.',
    group: 'Kết quả',
    order: 13,
    sourceLabels: ['Session 11'],
  },
  {
    id: 'interest',
    label: 'Lợi tức',
    shortLabel: 'z',
    summary: 'Phần lợi nhuận phải nhường cho tư bản cho vay để đổi lấy quyền sử dụng vốn.',
    group: 'Kết quả',
    order: 14,
    sourceLabels: ['Session 11'],
  },
  {
    id: 'market',
    label: 'Thị trường',
    shortLabel: 'Thị trường',
    summary: 'Không gian trao đổi nơi giá trị của hàng hóa chỉ được thực hiện khi có sức mua tương ứng.',
    group: 'Kết quả',
    order: 15,
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
  },
  {
    id: 'liquidity',
    label: 'Thanh khoản',
    shortLabel: 'Thanh khoản',
    summary: 'Khả năng biến tài sản thành tiền đúng lúc để chi trả nghĩa vụ và tiếp tục chu kỳ.',
    group: 'Kết quả',
    order: 16,
    sourceLabels: ['Case Alpha Corp', 'Capital Lab'],
  },
];

export const conceptMapOrder = learningConcepts.map((concept) => concept.id);

export const conceptLabelMap = Object.fromEntries(
  learningConcepts.map((concept) => [concept.id, concept.label]),
);

export function getConceptMeta(conceptId) {
  return learningConcepts.find((concept) => concept.id === conceptId);
}

