const option = (id, label) => ({ id, label });

export const questionBank = [
  {
    id: 'q01-money-capital-start',
    type: 'single-choice',
    conceptIds: ['money-capital', 'capital-circuit'],
    difficulty: 1,
    prompt: 'Trong tình huống Alpha Corp, khoản vay 10.000 tỷ xuất hiện trước hết như hình thái nào của tư bản?',
    options: [
      option('a', 'Tư bản sản xuất'),
      option('b', 'Tư bản hàng hóa'),
      option('c', 'Tư bản tiền tệ'),
      option('d', 'Lợi nhuận đã thực hiện'),
    ],
    correctAnswer: 'c',
    explanation: 'Khoản vay ban đầu tồn tại dưới dạng tiền để chuẩn bị mua đất, vật liệu, máy móc và sức lao động nên nó là T.',
    alphaCorpConnection: 'Nếu T chưa được ứng ra để mua đầu vào thì chu kỳ T → H → SX → H’ → T’ chưa thể bắt đầu.',
    commonWrongReasons: {
      a: 'Tư bản sản xuất chỉ xuất hiện sau khi tiền đã được chuyển hóa thành đầu vào và đi vào SX.',
      b: 'Tư bản hàng hóa là kết quả sau sản xuất, không phải điểm xuất phát.',
      d: 'Lợi nhuận chỉ có thể nói tới khi giá trị đã quay về và vượt quá vốn ứng trước.',
    },
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q02-general-formula',
    type: 'single-choice',
    conceptIds: ['capital-circuit', 'capital'],
    difficulty: 1,
    prompt: 'Công thức chung của tư bản nhấn mạnh vận động nào dưới đây?',
    options: [
      option('a', 'H → T → H'),
      option('b', 'T → H → T’'),
      option('c', 'SX → H → SX'),
      option('d', 'T → SX → T'),
    ],
    correctAnswer: 'b',
    explanation: 'Công thức chung của tư bản là T → H → T’, trong đó T’ lớn hơn T vì có phần giá trị tăng thêm.',
    alphaCorpConnection: 'Alpha Corp chỉ hoàn tất logic tư bản khi số tiền quay về lớn hơn vốn ứng trước, chứ không chỉ là đổi tiền lấy tài sản.',
    sourceLabels: ['Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q03-surplus-value-production',
    type: 'single-choice',
    conceptIds: ['surplus-value', 'productive-capital'],
    difficulty: 1,
    prompt: 'Giá trị thặng dư được tạo ra trực tiếp ở giai đoạn nào?',
    options: [
      option('a', 'Khi mua đầu vào T → H'),
      option('b', 'Trong quá trình sản xuất SX'),
      option('c', 'Khi bán hàng hóa H’ → T’'),
      option('d', 'Khi ngân hàng giải ngân khoản vay'),
    ],
    correctAnswer: 'b',
    explanation: 'Giá trị thặng dư được tạo ra trong SX thông qua việc sức lao động tạo ra giá trị mới lớn hơn giá trị của chính nó.',
    alphaCorpConnection: 'Khâu bán hàng chỉ thực hiện giá trị đã có; nó không tự tạo ra giá trị thặng dư mới cho Alpha Corp.',
    sourceLabels: ['Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q04-hprime-not-cash',
    type: 'true-false',
    conceptIds: ['commodity-capital', 'liquidity'],
    difficulty: 1,
    prompt: 'Đúng hay sai: Khi ba tòa tháp mới dừng ở phần thô, Alpha Corp đã có ngay lượng tiền đủ để trả lương vì tài sản của họ đã tăng.',
    correctAnswer: false,
    explanation: 'Tài sản dưới dạng H’ chưa tự động trở thành tiền mặt. Thanh khoản chỉ xuất hiện khi giá trị được thực hiện qua H’ → T’.',
    alphaCorpConnection: 'Đây chính là lý do doanh nghiệp có tài sản lớn nhưng vẫn rơi vào khủng hoảng chi trả.',
    sourceLabels: ['Case Alpha Corp', 'Capital Lab'],
    verificationStatus: 'verified',
  },
  {
    id: 'q05-space-condition-balance',
    type: 'single-choice',
    conceptIds: ['spatial-condition', 'money-capital', 'commodity-capital'],
    difficulty: 2,
    prompt: 'Điều kiện liên tục về mặt không gian đòi hỏi điều gì?',
    options: [
      option('a', 'Toàn bộ vốn phải tồn tại ở dạng hàng hóa để tối đa hóa lợi nhuận'),
      option('b', 'Tổng tư bản phải đồng thời phân bố ở nhiều hình thái khác nhau'),
      option('c', 'Doanh nghiệp phải mở rộng địa lý của dự án'),
      option('d', 'Chỉ cần giữ thật nhiều tiền dự phòng'),
    ],
    correctAnswer: 'b',
    explanation: 'Điều kiện không gian nói tới việc tổng tư bản phải tồn tại đồng thời ở các hình thái tiền tệ, sản xuất và hàng hóa.',
    alphaCorpConnection: 'Nếu Alpha Corp dồn gần hết vốn vào H’ thì phần T cần cho lương, lãi và vận hành sẽ thiếu hụt.',
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q06-time-condition-hprime',
    type: 'single-choice',
    conceptIds: ['temporal-condition', 'circulation-time'],
    difficulty: 2,
    prompt: 'Điều kiện liên tục về mặt thời gian bị đứt ở đâu khi căn hộ không bán được?',
    options: [
      option('a', 'Ở T → H vì doanh nghiệp không mua đất nữa'),
      option('b', 'Ở SX vì công nhân ngừng tạo giá trị mới'),
      option('c', 'Ở H’ → T’ vì giá trị chưa quay lại thành tiền'),
      option('d', 'Ở T’ → T vì tiền tự mất giá'),
    ],
    correctAnswer: 'c',
    explanation: 'Điều kiện thời gian nhấn mạnh các khâu phải nối tiếp nhau liên tục. Khi H’ không bán được, T’ không hình thành nên chu kỳ sau bị treo.',
    alphaCorpConnection: 'Đây là nút nghẽn trọng tâm đã được project xác minh cho Alpha Corp.',
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q07-turnover-formula',
    type: 'single-choice',
    conceptIds: ['capital-turnover', 'production-time', 'circulation-time'],
    difficulty: 1,
    prompt: 'Thời gian chu chuyển của tư bản bằng gì?',
    options: [
      option('a', 'Thời gian sản xuất + thời gian lưu thông'),
      option('b', 'Thời gian lao động + thời gian nghỉ'),
      option('c', 'Thời gian xây dựng + thời gian marketing'),
      option('d', 'Thời gian vay vốn + thời gian trả lãi'),
    ],
    correctAnswer: 'a',
    explanation: 'Chu chuyển tư bản tính cả phần tư bản nằm trong sản xuất lẫn phần tư bản nằm trong lưu thông.',
    alphaCorpConnection: 'Một dự án có sản xuất dài và bán hàng chậm sẽ kéo dài toàn bộ chu chuyển của Alpha Corp.',
    sourceLabels: ['Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q08-market-freeze-effect',
    type: 'single-choice',
    conceptIds: ['market', 'circulation-time', 'liquidity'],
    difficulty: 2,
    prompt: 'Thị trường bất động sản đóng băng tác động trực tiếp nhất đến đại lượng nào của Alpha Corp?',
    options: [
      option('a', 'Làm giảm thời gian sản xuất'),
      option('b', 'Làm tăng thời gian lưu thông'),
      option('c', 'Làm tăng ngay giá trị thặng dư'),
      option('d', 'Làm biến hàng hóa thành tiền nhanh hơn'),
    ],
    correctAnswer: 'b',
    explanation: 'Khi sức mua yếu, hàng hóa khó tiêu thụ nên thời gian lưu thông kéo dài và vòng quay vốn chậm lại.',
    alphaCorpConnection: 'Ba tòa tháp dừng ở dạng H’ lâu hơn, khiến chi trả lãi và lương bị căng thẳng.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q09-interest-origin',
    type: 'single-choice',
    conceptIds: ['interest', 'profit', 'surplus-value'],
    difficulty: 2,
    prompt: 'Lợi tức mà Alpha Corp phải trả cho ngân hàng, xét đến cùng, được nhường từ đâu?',
    options: [
      option('a', 'Từ vốn tự có của ngân hàng'),
      option('b', 'Từ giá trị thặng dư được tạo ra trong sản xuất'),
      option('c', 'Từ quá trình in tiền của Nhà nước'),
      option('d', 'Từ việc tài sản tự tăng giá bất kỳ'),
    ],
    correctAnswer: 'b',
    explanation: 'Lợi tức là một phần của lợi nhuận, mà lợi nhuận là hình thức biểu hiện của giá trị thặng dư.',
    alphaCorpConnection: 'Nếu H’ chưa bán được, Alpha Corp vẫn phải thanh toán nghĩa vụ lãi dù giá trị chưa quay về.',
    sourceLabels: ['Session 11', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q10-assets-vs-cash',
    type: 'single-choice',
    conceptIds: ['liquidity', 'commodity-capital'],
    difficulty: 2,
    prompt: 'Phát biểu nào diễn đạt đúng nhất sự khác biệt giữa “nhiều tài sản” và “có thanh khoản”?',
    options: [
      option('a', 'Có tài sản lớn thì luôn có thể dùng thay tiền ngay'),
      option('b', 'Thanh khoản đo khả năng biến tài sản thành tiền đúng lúc để đáp ứng nghĩa vụ'),
      option('c', 'Thanh khoản chỉ quan trọng với ngân hàng, không quan trọng với doanh nghiệp sản xuất'),
      option('d', 'Tài sản dở dang càng nhiều thì thanh khoản càng cao'),
    ],
    correctAnswer: 'b',
    explanation: 'Thanh khoản không đồng nhất với quy mô tài sản, mà gắn với khả năng chuyển thành tiền đúng thời điểm.',
    alphaCorpConnection: 'Alpha Corp có tài sản dở dang lớn nhưng vẫn thiếu tiền mặt để trả lương và lãi.',
    sourceLabels: ['Case Alpha Corp', 'Capital Lab'],
    verificationStatus: 'verified',
  },
  {
    id: 'q11-accumulation-condition',
    type: 'single-choice',
    conceptIds: ['accumulation', 'reproduction', 'surplus-value'],
    difficulty: 2,
    prompt: 'Điều kiện tiên quyết để tái sản xuất mở rộng là gì?',
    options: [
      option('a', 'Vay thêm vốn bất kể khả năng bán hàng'),
      option('b', 'Biến một phần giá trị thặng dư thành tư bản mới'),
      option('c', 'Giảm lương để tạo cảm giác lợi nhuận'),
      option('d', 'Giữ toàn bộ tiền trong trạng thái dự trữ'),
    ],
    correctAnswer: 'b',
    explanation: 'Tái sản xuất mở rộng đòi hỏi tích lũy, tức dùng một phần giá trị thặng dư để mở rộng quy mô tư bản.',
    alphaCorpConnection: 'Nếu Alpha Corp chưa chuyển H’ thành T’ thì cũng chưa thể nói tới tích lũy bền vững.',
    sourceLabels: ['Session 10'],
    verificationStatus: 'verified',
  },
  {
    id: 'q12-reproduction-break',
    type: 'true-false',
    conceptIds: ['reproduction', 'capital-turnover'],
    difficulty: 2,
    prompt: 'Đúng hay sai: Chỉ cần dự án từng tạo ra hàng hóa thì chu kỳ tái sản xuất sau sẽ tự động diễn ra, bất kể tiền có quay về hay không.',
    correctAnswer: false,
    explanation: 'Tái sản xuất chỉ lặp lại khi tư bản quay vòng thành công và có đủ điều kiện để bắt đầu chu kỳ mới.',
    alphaCorpConnection: 'Không có T’ quay về, Alpha Corp thiếu nguồn để mua đầu vào và duy trì vận động của vốn.',
    sourceLabels: ['Session 10', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q13-profit-vs-interest',
    type: 'multiple-choice',
    conceptIds: ['profit', 'interest'],
    difficulty: 3,
    prompt: 'Chọn tất cả phát biểu phù hợp với phân biệt giữa lợi nhuận và lợi tức.',
    options: [
      option('a', 'Lợi nhuận là hình thức biểu hiện ra ngoài của giá trị thặng dư'),
      option('b', 'Lợi tức là phần lợi nhuận phải nhường cho tư bản cho vay'),
      option('c', 'Lợi tức luôn được tạo ra ngoài sản xuất nên không liên hệ với giá trị thặng dư'),
      option('d', 'Doanh nghiệp có thể phải trả lợi tức ngay cả khi chưa thu được tiền bán hàng'),
    ],
    correctAnswer: ['a', 'b', 'd'],
    explanation: 'Lợi tức không tách rời giá trị thặng dư; nó là phần lợi nhuận phải nhường cho chủ nợ vốn.',
    alphaCorpConnection: 'Alpha Corp vẫn chịu nghĩa vụ lãi trong lúc H’ còn mắc kẹt ngoài thị trường.',
    sourceLabels: ['Session 11', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q14-order-cycle',
    type: 'ordering',
    conceptIds: ['capital-circuit'],
    difficulty: 2,
    prompt: 'Sắp xếp đúng trình tự vận động cơ bản của tư bản trong dự án Alpha Corp.',
    options: [
      option('t', 'T'),
      option('h', 'H'),
      option('sx', 'SX'),
      option('hp', 'H’'),
      option('tp', 'T’'),
    ],
    correctAnswer: ['t', 'h', 'sx', 'hp', 'tp'],
    explanation: 'Tư bản bắt đầu ở dạng tiền, đi qua mua đầu vào, sản xuất, xuất hiện dưới dạng hàng hóa rồi mới quay về tiền lớn hơn.',
    alphaCorpConnection: 'Sai thứ tự thường kéo theo nhầm lẫn giữa nơi tạo giá trị và nơi thực hiện giá trị.',
    sourceLabels: ['Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q15-space-condition-scenario',
    type: 'scenario',
    conceptIds: ['spatial-condition', 'liquidity', 'money-capital'],
    difficulty: 3,
    prompt: 'Alpha Corp dồn gần như toàn bộ vốn vào công trình dở dang, chỉ giữ lượng tiền rất mỏng. Kết luận nào sát nhất về điều kiện không gian?',
    options: [
      option('a', 'Điều kiện không gian được tăng cường vì tài sản vật chất nhiều hơn'),
      option('b', 'Điều kiện không gian bị mất cân đối vì thiếu phần tư bản tiền tệ để nối chu kỳ'),
      option('c', 'Không liên quan, vì điều kiện không gian chỉ nói về địa điểm xây dựng'),
      option('d', 'Đây chỉ ảnh hưởng đến lợi nhuận, không liên hệ thanh khoản'),
    ],
    correctAnswer: 'b',
    explanation: 'Điều kiện không gian đòi hỏi tư bản đồng thời tồn tại ở nhiều hình thái; dồn quá nhiều vào H’ sẽ làm thiếu T.',
    alphaCorpConnection: 'Đây là một mô tả trực tiếp của trạng thái thiếu thanh khoản trong case Alpha Corp.',
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q16-temporal-condition-scenario',
    type: 'scenario',
    conceptIds: ['temporal-condition', 'circulation-time', 'capital-turnover'],
    difficulty: 3,
    prompt: 'Công trình vẫn tiếp tục thi công nhưng lượng căn bán ra giảm mạnh, khiến tiền về chậm hơn nhiều. Đây là rủi ro nổi bật nào?',
    options: [
      option('a', 'Điều kiện thời gian bị căng vì H’ → T’ kéo dài'),
      option('b', 'Giá trị thặng dư tăng nhanh hơn'),
      option('c', 'Điều kiện không gian hoàn toàn không còn ý nghĩa'),
      option('d', 'Doanh nghiệp đã hoàn thành chu chuyển vốn'),
    ],
    correctAnswer: 'a',
    explanation: 'Điều kiện thời gian tập trung vào nhịp nối tiếp các khâu; bán chậm làm chu kỳ sau bị trì hoãn.',
    alphaCorpConnection: 'Đó là cách thị trường đóng băng chuyển thành khủng hoảng vận động vốn ở Alpha Corp.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q17-production-vs-circulation',
    type: 'multiple-choice',
    conceptIds: ['production-time', 'circulation-time', 'capital-turnover'],
    difficulty: 3,
    prompt: 'Chọn tất cả yếu tố làm kéo dài thời gian lưu thông nhiều hơn là thời gian sản xuất.',
    options: [
      option('a', 'Thị trường giảm sức mua, bán chậm'),
      option('b', 'Khó ký hợp đồng tiêu thụ để chuyển H’ thành tiền'),
      option('c', 'Quy trình thi công phần thô kéo dài vì kỹ thuật'),
      option('d', 'Người mua trì hoãn quyết định xuống tiền'),
    ],
    correctAnswer: ['a', 'b', 'd'],
    explanation: 'Các yếu tố liên quan tiêu thụ và thu tiền thuộc lưu thông; yếu tố kỹ thuật thi công thuộc sản xuất.',
    alphaCorpConnection: 'Case Alpha Corp nổi bật ở phần lưu thông bị ách tắc, không phải vì H’ chưa hề được tạo ra.',
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q18-commodity-vs-productive',
    type: 'single-choice',
    conceptIds: ['productive-capital', 'commodity-capital'],
    difficulty: 2,
    prompt: 'Điểm phân biệt đúng nhất giữa tư bản sản xuất và tư bản hàng hóa trong case Alpha Corp là gì?',
    options: [
      option('a', 'Tư bản sản xuất là tiền vay, tư bản hàng hóa là lãi phải trả'),
      option('b', 'Tư bản sản xuất tồn tại trong SX; tư bản hàng hóa là kết quả hàng hóa sau SX'),
      option('c', 'Hai khái niệm giống nhau, chỉ khác cách gọi'),
      option('d', 'Tư bản hàng hóa luôn có thanh khoản cao hơn tư bản sản xuất'),
    ],
    correctAnswer: 'b',
    explanation: 'Tư bản sản xuất nằm trong quá trình tạo ra giá trị mới; tư bản hàng hóa là sản phẩm mang giá trị sau sản xuất.',
    alphaCorpConnection: 'Ba tòa tháp phần thô là H’, không còn là bản thân quá trình SX nữa.',
    sourceLabels: ['Session 8', 'Capital Lab'],
    verificationStatus: 'verified',
  },
  {
    id: 'q19-liquidity-mistake',
    type: 'single-choice',
    conceptIds: ['liquidity', 'commodity-capital'],
    difficulty: 2,
    prompt: 'Nhầm lẫn nào dưới đây là sai lầm điển hình về thanh khoản?',
    options: [
      option('a', 'Cho rằng tài sản dở dang có thể thay thế ngay cho tiền lương đến hạn'),
      option('b', 'Xem việc bán chậm là yếu tố kéo dài lưu thông'),
      option('c', 'Nhận ra H’ chưa tự động là T’'),
      option('d', 'Phân biệt tài sản với tiền mặt'),
    ],
    correctAnswer: 'a',
    explanation: 'Tài sản dở dang có giá trị nhưng không tự động làm nghĩa vụ tiền mặt biến mất.',
    alphaCorpConnection: 'Đây là cách hiểu sai phổ biến khi nhìn case Alpha Corp chỉ qua quy mô tài sản.',
    sourceLabels: ['Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q20-case-decision-buffer',
    type: 'scenario',
    conceptIds: ['money-capital', 'liquidity', 'spatial-condition'],
    difficulty: 4,
    prompt: 'Trong một giai đoạn tín dụng bị siết, quyết định nào có logic học thuật thận trọng hơn để duy trì vận động của vốn?',
    options: [
      option('a', 'Dồn toàn lực mở rộng công trình để nhanh có nhiều hàng hóa hơn'),
      option('b', 'Giữ một phần tư bản tiền tệ để đảm bảo nghĩa vụ ngắn hạn và nối chu kỳ'),
      option('c', 'Bỏ hoàn toàn phần tiền lương để dồn vào vật liệu'),
      option('d', 'Xem thanh khoản là chuyện thứ yếu, chỉ cần tài sản tăng'),
    ],
    correctAnswer: 'b',
    explanation: 'Khi rủi ro lưu thông tăng, duy trì phần T đủ dùng giúp doanh nghiệp còn khả năng trả nghĩa vụ và tiếp tục chu kỳ.',
    alphaCorpConnection: 'Đây không phải tư vấn kinh doanh thực tế, mà là cách diễn giải điều kiện không gian trên case giả định.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q21-interest-before-sales',
    type: 'true-false',
    conceptIds: ['interest', 'liquidity'],
    difficulty: 2,
    prompt: 'Đúng hay sai: Nếu H’ chưa bán được thì Alpha Corp chưa cần đối mặt với áp lực lợi tức.',
    correctAnswer: false,
    explanation: 'Nghĩa vụ lãi tồn tại theo hạn vay, không chờ doanh nghiệp bán xong hàng hóa mới phát sinh.',
    alphaCorpConnection: 'Đó là lý do đứt thanh khoản nhanh chóng biến thành sức ép nợ.',
    sourceLabels: ['Case Alpha Corp', 'Session 11'],
    verificationStatus: 'verified',
  },
  {
    id: 'q22-market-liquidity-links',
    type: 'multiple-choice',
    conceptIds: ['market', 'liquidity', 'circulation-time'],
    difficulty: 3,
    prompt: 'Chọn tất cả nhận định đúng về liên hệ giữa thị trường và thanh khoản trong case Alpha Corp.',
    options: [
      option('a', 'Thị trường yếu có thể khiến H’ nằm lâu hơn ngoài lưu thông'),
      option('b', 'Thanh khoản tốt chỉ phụ thuộc vào quy mô tài sản đang xây dở'),
      option('c', 'Khi sức mua suy giảm, H’ → T’ trở nên khó khăn hơn'),
      option('d', 'Thị trường đóng băng có thể kéo dài thời gian lưu thông'),
    ],
    correctAnswer: ['a', 'c', 'd'],
    explanation: 'Thị trường ảnh hưởng trực tiếp đến khả năng thực hiện giá trị và do đó ảnh hưởng đến thanh khoản.',
    alphaCorpConnection: 'Alpha Corp mắc nghẽn vì thị trường không hấp thụ được lượng hàng hóa đã tạo ra.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q23-order-break-consequence',
    type: 'ordering',
    conceptIds: ['capital-turnover', 'liquidity', 'temporal-condition'],
    difficulty: 4,
    prompt: 'Sắp xếp chuỗi hệ quả hợp lý nhất khi H’ không bán được trong thời gian dài.',
    options: [
      option('a', 'Thanh khoản giảm'),
      option('b', 'T’ quay về chậm'),
      option('c', 'Chu kỳ tái sản xuất sau bị chậm'),
      option('d', 'Nghĩa vụ ngắn hạn trở nên căng'),
    ],
    correctAnswer: ['b', 'a', 'd', 'c'],
    explanation: 'H’ bán chậm khiến T’ quay về trễ; từ đó thanh khoản suy yếu, nghĩa vụ ngắn hạn căng lên và chu kỳ sau bị chậm.',
    alphaCorpConnection: 'Đây là cách đọc logic “đứt gãy H’ → T’” theo chuỗi tác động, không chỉ theo một điểm tĩnh.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q24-accumulation-vs-hoarding',
    type: 'single-choice',
    conceptIds: ['accumulation', 'reproduction', 'money-capital'],
    difficulty: 3,
    prompt: 'Phát biểu nào phân biệt đúng giữa tích lũy tư bản và việc chỉ giữ tiền bất động?',
    options: [
      option('a', 'Tích lũy là biến một phần giá trị thặng dư thành tư bản mới để mở rộng vận động'),
      option('b', 'Tích lũy là cất tiền lại và không cho nó tham gia chu kỳ nữa'),
      option('c', 'Tích lũy và thanh khoản là một khái niệm'),
      option('d', 'Tích lũy chỉ diễn ra trong lưu thông, không liên quan sản xuất'),
    ],
    correctAnswer: 'a',
    explanation: 'Tích lũy gắn với việc mở rộng tư bản, chứ không phải đóng băng giá trị dưới dạng cất trữ thụ động.',
    alphaCorpConnection: 'Alpha Corp chỉ có thể nói tới tích lũy khi giá trị đã thực hiện xong và một phần được tái đầu tư.',
    sourceLabels: ['Session 10'],
    verificationStatus: 'verified',
  },
  {
    id: 'q25-reproduction-loop',
    type: 'single-choice',
    conceptIds: ['reproduction', 'capital-circuit'],
    difficulty: 3,
    prompt: 'Tái sản xuất trong bối cảnh website này nên được hiểu gần nhất là gì?',
    options: [
      option('a', 'Một lần xây xong dự án là kết thúc toàn bộ vận động'),
      option('b', 'Quá trình chu kỳ vốn được lặp lại để duy trì hoặc mở rộng sản xuất'),
      option('c', 'Chỉ là việc nhân bản hàng hóa về số lượng'),
      option('d', 'Chỉ nói tới việc ngân hàng phát hành thêm tín dụng'),
    ],
    correctAnswer: 'b',
    explanation: 'Tái sản xuất nhấn mạnh việc chu kỳ vốn được lặp lại, không phải một biến cố sản xuất đơn lẻ.',
    alphaCorpConnection: 'Nếu T’ không quay về, Alpha Corp thậm chí khó duy trì cả tái sản xuất giản đơn.',
    sourceLabels: ['Session 10', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q26-weakest-link',
    type: 'scenario',
    conceptIds: ['commodity-capital', 'liquidity', 'capital-turnover'],
    difficulty: 4,
    prompt: 'Nếu một người nói “Alpha Corp giàu lên vì đã có nhiều công trình dở dang hơn”, phản hồi học thuật chặt hơn là gì?',
    options: [
      option('a', 'Đúng, vì càng nhiều H’ thì tiền mặt càng chắc chắn tăng'),
      option('b', 'Chưa thể kết luận, vì H’ chưa thực hiện được giá trị thì doanh nghiệp vẫn có thể thiếu thanh khoản'),
      option('c', 'Đúng, vì sản xuất luôn quan trọng hơn lưu thông'),
      option('d', 'Không cần xét đến T’ vì tài sản đã đủ lớn'),
    ],
    correctAnswer: 'b',
    explanation: 'Quy mô H’ không tự bảo đảm thanh khoản. Cần xem giá trị có thực hiện được thành T’ hay không.',
    alphaCorpConnection: 'Đây là câu hỏi lõi giúp phân biệt tài sản với tiền mặt trong case Alpha Corp.',
    sourceLabels: ['Case Alpha Corp', 'Capital Lab'],
    verificationStatus: 'verified',
  },
  {
    id: 'q27-spatial-temporal-separate',
    type: 'multiple-choice',
    conceptIds: ['spatial-condition', 'temporal-condition'],
    difficulty: 4,
    prompt: 'Chọn các mô tả đúng về khác biệt giữa điều kiện không gian và điều kiện thời gian.',
    options: [
      option('a', 'Điều kiện không gian hỏi tư bản đang được phân bố đồng thời ra sao giữa các hình thái'),
      option('b', 'Điều kiện thời gian hỏi các khâu có nối tiếp kịp để chu kỳ sau khởi động hay không'),
      option('c', 'Điều kiện không gian chỉ nói về vị trí địa lý xây dựng dự án'),
      option('d', 'Điều kiện thời gian chỉ cần nhìn vào một thời điểm tĩnh mà không xét nhịp quay vòng'),
    ],
    correctAnswer: ['a', 'b'],
    explanation: 'Không gian nói tới cơ cấu đồng thời của các hình thái tư bản; thời gian nói tới nhịp nối tiếp và độ trễ của chu kỳ.',
    alphaCorpConnection: 'Alpha Corp vừa có nguy cơ mất cân đối hình thái vốn, vừa có nguy cơ chu kỳ quay lại quá chậm.',
    sourceLabels: ['Session 8', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q28-profit-not-sales-only',
    type: 'single-choice',
    conceptIds: ['profit', 'surplus-value', 'capital-circuit'],
    difficulty: 3,
    prompt: 'Lập luận nào chặt hơn về lợi nhuận của Alpha Corp?',
    options: [
      option('a', 'Chỉ cần giá bán cao là tự động có lợi nhuận bền vững'),
      option('b', 'Lợi nhuận phải được nhìn trong quan hệ với toàn bộ tư bản ứng trước và việc thực hiện giá trị'),
      option('c', 'Lợi nhuận không liên quan gì đến lưu thông'),
      option('d', 'Lợi nhuận và lợi tức là cùng một đại lượng'),
    ],
    correctAnswer: 'b',
    explanation: 'Lợi nhuận là hình thức biểu hiện của giá trị thặng dư trên toàn bộ tư bản ứng trước và còn phụ thuộc việc giá trị có được thực hiện hay không.',
    alphaCorpConnection: 'Bán chậm hoặc không bán được sẽ làm phần “lợi nhuận kỳ vọng” của Alpha Corp không thể hiện thực.',
    sourceLabels: ['Session 11', 'Case Alpha Corp'],
    verificationStatus: 'verified',
  },
  {
    id: 'q29-case-recovery',
    type: 'scenario',
    conceptIds: ['liquidity', 'capital-circuit', 'reproduction'],
    difficulty: 4,
    prompt: 'Theo logic học thuật của project, đâu là điều kiện cốt lõi để Alpha Corp có thể mở lại vòng tái sản xuất tiếp theo?',
    options: [
      option('a', 'Tiếp tục tăng khối lượng công trình dở dang'),
      option('b', 'Khơi thông khả năng chuyển H’ thành T’ để tiền quay về'),
      option('c', 'Bỏ qua nghĩa vụ lãi để tập trung xây tiếp'),
      option('d', 'Giữ nguyên mọi tài sản ở dạng hiện tại vì chúng đã có giá trị'),
    ],
    correctAnswer: 'b',
    explanation: 'Chu kỳ tiếp theo cần tiền quay về để mua lại đầu vào và duy trì nghĩa vụ; nút này nằm ở H’ → T’.',
    alphaCorpConnection: 'Đây là nội dung được source of truth của project nêu rõ như nút nghẽn trọng tâm.',
    sourceLabels: ['Case Alpha Corp', 'docs/02-ACADEMIC-SOURCE-OF-TRUTH.md'],
    verificationStatus: 'verified',
  },
  {
    id: 'q30-market-not-perfect',
    type: 'single-choice',
    conceptIds: ['market', 'liquidity'],
    difficulty: 3,
    prompt: 'Câu nào phản ánh đúng nhất vai trò của thị trường trong case Alpha Corp?',
    options: [
      option('a', 'Thị trường luôn hấp thụ hàng hóa nếu hàng hóa có giá trị'),
      option('b', 'Thị trường là nơi giá trị chỉ được thực hiện khi có sức mua tương ứng'),
      option('c', 'Thị trường không ảnh hưởng tới chu chuyển tư bản'),
      option('d', 'Thị trường chỉ quyết định lợi tức, không liên quan thanh khoản'),
    ],
    correctAnswer: 'b',
    explanation: 'Giá trị của hàng hóa không tự thực hiện; cần có sức mua thực tế trên thị trường.',
    alphaCorpConnection: 'Sự đứt gãy của Alpha Corp đến từ việc hàng hóa không được hấp thụ đủ nhanh.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
  {
    id: 'q31-review-liquidity-cluster',
    type: 'multiple-choice',
    conceptIds: ['liquidity', 'market', 'commodity-capital'],
    difficulty: 4,
    prompt: 'Chọn các dấu hiệu cho thấy Alpha Corp đang bị kẹt ở cụm vấn đề thanh khoản thay vì chỉ thiếu “tài sản”.',
    options: [
      option('a', 'Có nghĩa vụ lãi và lương đến hạn trong khi tiền về chậm'),
      option('b', 'Hàng hóa dở dang có giá trị nhưng khó tiêu thụ'),
      option('c', 'Doanh nghiệp đã có thêm nhiều tài sản nên chắc chắn chi trả dễ hơn'),
      option('d', 'Thời gian lưu thông kéo dài làm chu kỳ vốn chậm lại'),
    ],
    correctAnswer: ['a', 'b', 'd'],
    explanation: 'Cụm vấn đề thanh khoản bộc lộ khi nghĩa vụ tiền mặt đến hạn nhưng giá trị chưa chuyển hóa thành tiền.',
    alphaCorpConnection: 'Đây là mô tả cô đọng của điểm đứt gãy H’ → T’.',
    sourceLabels: ['Case Alpha Corp', 'Capital Lab'],
    verificationStatus: 'verified',
  },
  {
    id: 'q32-advanced-balance',
    type: 'scenario',
    conceptIds: ['spatial-condition', 'temporal-condition', 'liquidity'],
    difficulty: 5,
    prompt: 'Một quyết định “đẩy thật nhanh phần thi công để bù cho bán chậm” có rủi ro lý luận nào nếu không tăng được sức mua?',
    options: [
      option('a', 'Có thể làm H’ tích tụ thêm, làm mất cân đối không gian và kéo dài tắc nghẽn thời gian'),
      option('b', 'Chắc chắn khôi phục T’ vì sản xuất luôn giải quyết được lưu thông'),
      option('c', 'Không ảnh hưởng gì đến thanh khoản miễn là tài sản tăng'),
      option('d', 'Tự động biến lợi tức thành lợi nhuận'),
    ],
    correctAnswer: 'a',
    explanation: 'Nếu đầu ra không tiêu thụ được, tăng thêm H’ có thể khiến tư bản càng dồn vào hàng hóa và làm chu kỳ quay về chậm hơn.',
    alphaCorpConnection: 'Đây là dạng đánh đổi quan trọng sẽ được dùng lại trong Case Mission.',
    sourceLabels: ['Case Alpha Corp', 'Session 8'],
    verificationStatus: 'verified',
  },
];

export const verifiedQuestionBank = questionBank.filter(
  (question) => question.verificationStatus === 'verified',
);

export const questionMap = new Map(verifiedQuestionBank.map((question) => [question.id, question]));

export function getQuestionById(questionId) {
  return questionMap.get(questionId);
}

export const dailyChallengeQuestionIds = [
  'q08-market-freeze-effect',
  'q15-space-condition-scenario',
  'q16-temporal-condition-scenario',
  'q20-case-decision-buffer',
  'q23-order-break-consequence',
  'q27-spatial-temporal-separate',
  'q29-case-recovery',
  'q32-advanced-balance',
];

